### PR TITLE
Add igvxml

### PR DESCRIPTION
**Pull request by smondet**
This version works only with `b37decoy` and `mm10` (tool's choice).
But it works™ :)

I didn't add to the TTFI EDSL because I don't see the use case.

Also, the results depends on the paths not on the contents of the files at that path (they can run even if they don't exist), so the tool does not depend on the bam/vcf products.

---
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/biokepi/316)

### CODE REVIEW

**Comment by smondet** [comment]
One funny thing, if called with `b37`, it still silently works with `b37decoy` because Cmdliner compares prefixes for everything.

**Comment by ihodes** [comment]
LGTM. 

Why not add it to the TTFI?

**Comment by smondet** [comment]
@ihodes for now I'm using it **as part of** an extension to the TTFI, but  by itself it doesn't make much sense becase there is no "pipeline" i.e. no dependencies, it's all strings, the API would be

```ocaml
val igvxml:
   normal_bam_path: string ->
   tumor_bam_path: string ->
   ... (* no repr at all *)
   -> [ `Igv_xml ] repr
```

**Comment by ihodes** [comment]
Ah, I see what you mean. The downside to this is as a consumer of the TTFI, you'd need to write a fair amount of code to be able to use this in your own pipeline, right?

**Comment by smondet** [comment]
Even in the TTFI, as is, it would be pretty awkward to use. You need to give paths that depend on the backend actually running (in our case choices made in `Biokepi.Tools`) and on top of that you may have to transform those paths to something else (in my case relative paths from the place the results are save, not computed; but it may also be that you have to transform into HTTP URLs (?)).
Within a TTFI pipeline those considerations are too low-level, aren't they?

**Comment by ihodes** [comment]
Hmm, not really sure—the alternative is cumbersome. Regardless, this looks good, and thank you for adding it!

**Pull request merged**
