### PR TITLE
Add bedtools and bamtofastq

### PR DESCRIPTION
**Pull request by arahuja**
[Review on Reviewable](https://reviewable.io/reviews/hammerlab/biokepi/39)

### CODE REVIEW

**Comment by hammer** [comment]
Why use `samtools` for `bam2fastq` and not ADAM?

**Comment by arahuja** [comment]
I actually did use ADAM, but implemented this first so am submitting anyways.

**Comment by hammer** [comment]
Hmm interesting then we'll have a naming conflict in the space of `biokepi` targets. @smondet do you have any thoughts on how targets in `biokepi` should be organized into namespaces?

**Comment by smondet** [comment]
@arahuja  Thanks

@hammer it used to be complete anarchy, and @arahuja started organizing into modules, we should keep going that way.

ADAM requires more "system admin" support than Biokepi has so far, discussion there: https://github.com/hammerlab/biokepi/issues/30

**Pull request merged**
