### PR TITLE
WIP: QC improvements

### PR DESCRIPTION
**Pull request by armish**
This PR will provide additional QC functionalities via:

 - MultiQC (for unification of the reports)
 - QualiMap (for simple coverage stats)
 - Samtools stats (in addition to current flagstats)
 - Cloml (for purity estimation from VCFs)

### CODE REVIEW

**Comment by hammer** [comment]
@armish is this PR blocking on anything?

**Comment by armish** [comment]
@hammer: nope — it is just that I wasn't able to get to this due to other things taking priority over these improvements.

**Comment by ihodes** [comment]
If you're thinking of adding more… :) https://github.com/hammerlab/biokepi/issues/408

**Comment by armish** [comment]
@tavinathanson: Thanks for mentioning [RNA-seqc](http://archive.broadinstitute.org/cancer/cga/rna-seqc), I will definitely give that a try and add it to the list if the reports look promising.

**Comment by armish** [comment]
I am going to close this one down and continue the work over the condafication front (#468) since that will be making things much easier for us.

**Pull request closed without merging**
