### PR TITLE
Use the version string in the Conda environment

### PR DESCRIPTION
**Pull request by smondet**
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/biokepi/319)

### CODE REVIEW

**Comment by ihodes** [comment]
LGTM

might be a good addition for Conda.setup_env?

**Comment by smondet** [comment]
@ihodes what do you mean?

**Comment by ihodes** [comment]
`Conda.setup_environment ?version …` instead of manually adding it to the name?

**Comment by smondet** [comment]
@ihodes but the `version` is the version of the package. We happen to create one Conda env per package because it doesn't really work to share them; but from Conda's point of view it's just an environment with a name.
Cf. the `Biopam` module which has a somewhat different use of `Conda`:
https://github.com/hammerlab/biokepi/blob/master/src/environment_setup/biopam.ml#L200
(no `version` there).

**Pull request merged**
