### PR TITLE
Fixing b37 Broad links.

### LINKED ISSUE #469: Biokepi dbsnp download fails
The `wget-dbsnp.vcf.gz` task fails with:
```
--2017-05-17 23:40:20--  ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/2.8/b37/dbsnp_138.b37.vcf.gz
           => '/mnt/fuzzy-nfs/nfs-pool/biokepi-work-dir/reference-genome/b37decoy/dbsnp.vcf.gz'
Resolving ftp.broadinstitute.org (ftp.broadinstitute.org)... 69.173.80.251
Connecting to ftp.broadinstitute.org (ftp.broadinstitute.org)|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /bundle/2.8/b37 ... 
No such directory 'bundle/2.8/b37'.
```

### PR DESCRIPTION
**Pull request by julia326**
Fixes #469

### CODE REVIEW

**Comment by ihodes** [comment]
Thanks for doing this! Could you point them at our raw_data bucket instead? That way we know the links won't change.

**Comment by julia326** [comment]
no prob! does this understand gs:// links, or should I use https://console.cloud.google.com/storage/browser/hammerlab-biokepi-data/raw_data?

**Comment by smondet** [comment]
@julia326 on the gcloud UI there is a `"Public Link"` link, that's the one we should use.

**Comment by ihodes** [comment]
LGTM! Thanks for fixing.

**Pull request merged**
