### PR TITLE
Use a GADT to model the germline & somatic variant calling distinction

### PR DESCRIPTION
**Pull request by rleonid**
a WIP.

---
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/biokepi/178)

### CODE REVIEW

**Comment by iskandr** [comment]
I don't know if the old code handled this, but I just wanted to point out that Varscan2 has distinct modes for [single-sample variant calling](http://varscan.sourceforge.net/using-varscan.html#v2.3_pileup2snp),  [multi-sample variant calling](http://varscan.sourceforge.net/using-varscan.html#v2.3_mpileup2snp) and [somatic tumor/normal variant calling](http://varscan.sourceforge.net/using-varscan.html#v2.3_somatic). 

I'm not sure if these should be treated as different tools in Biokepi.

**Comment by iskandr** [comment]
Just in case that's not enough, Varscan2 also calls copy numbers (http://varscan.sourceforge.net/using-varscan.html#v2.3_copynumber), though apparently only for tumor/normal somatic samples.

**Comment by rleonid** [comment]
@iskandr Perhaps filing an issue so that we don't forget. Adding new types of variant calling is outside the scope of this line of work; which is to further understanding by simplifying the code.

**Comment by smondet** [comment]
@iskandr that's why the functions are called `Varscan.somatic_*`, it's the only case implemented so far but we can add the other ones
https://github.com/hammerlab/biokepi/blob/master/src/lib/varscan.ml#L104

**Pull request merged**
