### PR TITLE
Make biokepi use master branch igvxml

### PR DESCRIPTION
**Pull request by ihodes**

### CODE REVIEW

**Comment by smondet** [comment]
I'm not sure it's a good idea to use for the "defaults."

You can force the `master` branch to be used in your biokepi machine.

**Comment by ihodes** [comment]
Should I just use a commit in this case (to use a newer version of igvxml?)

**Comment by hammer** [comment]
@ihodes why not just cut a release of igvxml?

**Comment by ihodes** [comment]
Because updating on opam is kind of a pain for no benefit right now, and I anticipate continuing to change igvxml (lots of features need to be added) quite a bit in the near future for other uses of it.

**Comment by hammer** [comment]
Now that we have real patients in the pipeline I'd prefer we rely on released versions of software that can be recorded to improve reproducibility.

I also feel like a lot of pain for new users is caused by pinning.

**Comment by ihodes** [comment]
Gotcha—this is totally separate from the user needing to pin anything or know about what's happening. Biokepi pins to a commit here, and the commit hash would be noted so it's entirely reproducible.

**Comment by smondet** [comment]
@ihodes 

> I anticipate continuing to change igvxml (lots of features need to be added)

for that the best is using your `Biokepi.Machine.t` to force the one you want.

-----

I agree with @hammer the defaults should be proper releases (with `opam-publish` the release process is pretty fast also).

**Comment by ihodes** [comment]
> for that the best is using your Biokepi.Machine.t to force the one you want.

This is something I want all users to have, since it's effectively broken. 

opam-publish isn't fast: it requires manual review. 

Is there any reason to not be okay using a git tag or commit? As far as I can tell, it 100% addresses any concerns either of you have?

**Comment by smondet** [comment]
> This is something I want all users to have…

That's why it's called "Release" ;)

> 
> opam-publish isn't fast: it requires manual review.

Well fully-automated could only be wrong…

> 
> Is there any reason to not be okay using a git tag or commit? As far as I can
> tell, it 100% addresses any concerns either of you have?

A github-only release (glorified tag) works for me.
A bit sad to not push to the mothership opam-repo.

**Comment by ihodes** [comment]
Cool, I'll push a tag out for this commit.

**Comment by hammer** [comment]
Please also try to release regularly to OPAM as well.

**Comment by ihodes** [comment]
@smondet back to you!

**Pull request merged**
